### PR TITLE
use cljs.core/distructed function to extract symbols from bingings

### PR DESCRIPTION
**Pull request by sbondaryev**
Issue: https://github.com/hoplon/javelin/issues/29

### CODE REVIEW

**Comment by sbondaryev** [comment]
Is the project still maintained?
Any questions or propositions about this PR?
Shall I close it?

**Comment by onetom** [comment]
I keep hitting the same issue, so this should definitely be merged eventually.
I guess we are just a bit busy with other things.
Whenever I hit this issue, I just fall back to the more verbose sym-kw pair style.

**Comment by sbondaryev** [comment]
ok, let me know if you want me make some corrections or explanations

**Comment by micha** [comment]
Looks great to me, thanks @sbondaryev!

**Comment by micha** [comment]
Extra points for adding tests, too :+1:

**Pull request merged**
